export default {
  docs: 'https://neon.tech/docs/introduction/about/',
  aboutUs: 'https://neon.tech/about-us/',
  careers: 'https://neon.tech/careers/',
  blog: 'https://neon.tech/blog/',
  signup: 'https://console.neon.tech/sign_in',
  security: 'https://neon.tech/docs/security/security/',
  releaseNotes: 'https://neon.tech/docs/release-notes/',
  discord: 'https://discord.gg/YKY4CBXZT2',
  discussions: 'https://github.com/neondatabase/neon/discussions',
  discourse: 'https://community.neon.tech',
  github: 'https://github.com/neondatabase/neon',
  twitter: 'https://twitter.com/neondatabase/',
  linkedin: 'https://www.linkedin.com/company/neon-inc/',
  youtube: 'https://www.youtube.com/channel/UCoMzQTJSIr7-RU1QbomQI2w',
  postgresDocs: 'https://www.postgresql.org/docs/',
  postgresList: 'https://www.postgresql.org/list/',
  privacy: 'https://neon.tech/privacy-policy',
  terms: 'https://neon.tech/terms-of-service',
  dashboard: 'https://console.neon.tech/sign_in',
  branching: 'https://neon.tech/branching/',
  contactSales: 'https://neon.tech/contact-sales/',
};
